version: '3.8'
services:
  fast-n-foodious-ms-pedido:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-n-foodious-ms-pedido
    env_file:
      - ./envs/${NODE_ENV:-prod}.env
    ports:
      - ${SERVER_PORT:-3001}:${SERVER_PORT:-3001}
    depends_on:
      - mysql-pedido
      - localstack
    networks:
      - fast-n-foodious-network
    environment:
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: overwrote-in-deployment-time
      AWS_SECRET_ACCESS_KEY: overwrote-in-deployment-time
      SQS_SOLICITAR_PAGAMENTO_REQ_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/solicitar-pagamento-req.fifo
      SQS_WEBHOOK_PAGAMENTO_CONFIRMADO_RES_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/webhook-pagamento-confirmado-res
      SQS_WEBHOOK_PAGAMENTO_REJEITADO_RES_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/webhook-pagamento-rejeitado-res
      SQS_PREPARACAO_PEDIDO_REQ_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/preparacao-pedido-req.fifo
      SQS_LGPD_PROTOCOLO_DELECAO_REQ_URL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/lgpd-protocolo-delecao-req.fifo
      SES_SOURCE_EMAIL: sac.fast.n.foodious@gmail.com
  mysql-pedido:
    image: mysql:8.0
    container_name: mysql-pedido
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_TCP_PORT: ${MYSQL_PORT:-3307}
    ports:
      - ${MYSQL_PORT:-3307}:${MYSQL_PORT:-3307}
    volumes:
      - ./scripts/schema:/docker-entrypoint-initdb.d
      - mysql-data-pedido:/data/db
    networks:
      - fast-n-foodious-network
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs,ses
      - MAIN_CONTAINER_NAME=localstack
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack/init-queues.sh:/etc/localstack/init/ready.d/init-queues.sh:rw
    networks:
      - fast-n-foodious-network
volumes:
  mysql-data-pedido:
  localstack-data:
networks:
  fast-n-foodious-network:
    driver: bridge