apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - name: {{ .Values.application.name }}
        image: {{ .Values.application.image }}
        resources:
          limits:
            memory: {{ .Values.application.resources.limits.memory }}
            cpu: {{ .Values.application.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            port: 3001
            path: /api
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 3001
            path: /api
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 3001
        envFrom:
          - configMapRef:
              name: {{ .Values.application.name }}-env
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-secret
                key: MYSQL_PASSWORD
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.application.name }}-env
                key: SERVER_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.image }}
        resources:
          limits:
            memory: {{ .Values.mysql.resources.limits.memory }}
            cpu: {{ .Values.mysql.resources.limits.cpu }}
        ports:
          - containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: {{ .Values.application.name }}-env
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.application.name }}-secret
                key: MYSQL_PASSWORD
        volumeMounts:
          - name: {{ .Values.application.name }}-mysql-init
            mountPath: /docker-entrypoint-initdb.d
          - name: {{ .Values.application.name }}-volume
            mountPath: {{ .Values.mysql.mountPath }}
      volumes:
        - name: {{ .Values.application.name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: {{ .Values.application.name }}-mysql-init
          configMap:
            name: {{ .Values.mysql.name }}-env
            items:
              - key: init.sql
                path: 1-init.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 4566
        livenessProbe:
          tcpSocket:
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: {{ .Values.application.name }}-env
        env:
          - name: DEBUG
            value: '0'
          - name: SERVICES
            value: sqs,ses
          - name: MAIN_CONTAINER_NAME
            value: localstack
        volumeMounts:
          - name: {{ .Values.application.name }}-localstack-init
            mountPath: /etc/localstack/init/ready.d
          - name: {{ .Values.application.name }}-localstack
            mountPath: /var/lib/localstack
      volumes:
        - name: {{ .Values.application.name }}-localstack
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: {{ .Values.application.name }}-localstack-init
          configMap:
            name: {{ .Values.mysql.name }}-env
            defaultMode: 0777
            items:
              - key: init.sh
                path: init-queues.sh                