apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.loadbalancer.port }}
    nodePort: 30001
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: 3306

