apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-ms-pedido-svc
spec:
  selector:
    app: fast-n-foodious-ms-pedido
  type: LoadBalancer
  ports:
  - port: 3001
    nodePort: 30001
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-pedido
spec:
  selector:
    app: mysql-pedido
  ports:
  - port: 3306

