apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-n-foodious-ms-pedido-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-n-foodious-ms-pedido-storage
  hostPath:
     path: /Users/renatorodrigues/mysql-pedido
     type: DirectoryOrCreate