apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-n-foodious-ms-pedido-env
data:
  MYSQL_DATABASE: FAST_N_FOODIOUS
  MYSQL_HOST: mysql-pedido
  MYSQL_PORT: '3306'
  MYSQL_USER: fnf_user
  MYSQL_ROOT_HOST: '%'
  NODE_ENV: prod
  SERVER_PORT: '3001'
  AWS_ENDPOINT: http://localstack:4566
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: overwrote-in-deployment-time
  AWS_SECRET_ACCESS_KEY: overwrote-in-deployment-time
  SQS_SOLICITAR_PAGAMENTO_REQ_URL: http://localstack:4566/000000000000/solicitar-pagamento-req.fifo
  SQS_WEBHOOK_PAGAMENTO_CONFIRMADO_RES_URL: http://localstack:4566/000000000000/webhook-pagamento-confirmado-res
  SQS_WEBHOOK_PAGAMENTO_REJEITADO_RES_URL: http://localstack:4566/000000000000/webhook-pagamento-rejeitado-res
  SQS_PREPARACAO_PEDIDO_REQ_URL: http://localstack:4566/000000000000/preparacao-pedido-req.fifo
  SQS_LGPD_PROTOCOLO_DELECAO_REQ_URL: http://localstack:4566/000000000000/lgpd-protocolo-delecao-req.fifo
  SES_SOURCE_EMAIL: sac.fast.n.foodious@gmail.com  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pedido-env
data:
  init.sql: |
    -- Criação de banco de dados
    CREATE DATABASE IF NOT EXISTS FAST_N_FOODIOUS;

    -- Configuração de permissão para usuário da aplicação
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES ON FAST_N_FOODIOUS.* TO 'fnf_user'@'%';
    FLUSH PRIVILEGES;

    USE FAST_N_FOODIOUS;

    --
    -- CRIAÇÃO DE TABELAS
    --

    -- Tabela cliente
    CREATE TABLE IF NOT EXISTS CLIENTE (
                                          ID INT AUTO_INCREMENT PRIMARY KEY,
                                          NOME VARCHAR(255) NOT NULL,
                                          EMAIL VARCHAR(255) NOT NULL,
                                          CPF VARCHAR(11) NOT NULL
    );

    -- indexes para tabela CLIENTE
    CREATE UNIQUE INDEX cliente_email_idx ON CLIENTE(EMAIL);
    CREATE UNIQUE INDEX cliente_cpf_idx ON CLIENTE(CPF);

    --  Criando um usuário pré-definido para ser utilizado na deleção de clientes
    --  (antes de um cliente ser deletado fisicamente, todos os pedidos a ele associados são atualizados para se relacionarem
    --  com o usuário pré-definido)
    INSERT IGNORE INTO
        CLIENTE (ID, NOME, EMAIL, CPF)
    VALUES (1, 'Usuário Deletado (LGPD)', 'deletado.lgpd@fnf.com', '00000000191');

    -- Tabela PEDIDO
    CREATE TABLE IF NOT EXISTS PEDIDO (
                                          ID INT AUTO_INCREMENT PRIMARY KEY,
                                          PEDIDO_CLIENTE_ID INT NOT NULL, CONSTRAINT FK_PEDIDO_CLIENTE_ID FOREIGN KEY (PEDIDO_CLIENTE_ID) REFERENCES CLIENTE(ID),
                                          DATA_INICIO VARCHAR(255) NOT NULL,
                                          ESTADO_PEDIDO INT NOT NULL,
                                          ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
                                          TOTAL DECIMAL(8,2) NULL
    );

    -- Tabela ITEMS DE PEDIDO
    CREATE TABLE IF NOT EXISTS ITEM_PEDIDO (
                                          ID INT AUTO_INCREMENT PRIMARY KEY,
                                          PEDIDO_ID INT NOT NULL, CONSTRAINT FK_PEDIDO_ID FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
                                          PRODUTO_ID INT NOT NULL,
                                          QUANTIDADE INT NOT NULL
    );
  init.sh: |
    #!/bin/bash
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name sqs-dlq.fifo --attributes "FifoQueue=true","DelaySeconds=0"
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name sqs-dlq --attributes "DelaySeconds=0"

    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name webhook-pagamento-rejeitado-res --attributes '{"RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-dlq\",\"maxReceiveCount\":\"3\"}","VisibilityTimeout":"1"}'
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name webhook-pagamento-confirmado-res --attributes '{"RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-dlq\",\"maxReceiveCount\":\"3\"}","VisibilityTimeout":"1"}'
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name solicitar-pagamento-req.fifo --attributes '{"FifoQueue":"true","RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-dlq.fifo\",\"maxReceiveCount\":\"3\"}","VisibilityTimeout":"1"}'
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name preparacao-pedido-req.fifo --attributes '{"FifoQueue":"true","RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-dlq.fifo\",\"maxReceiveCount\":\"3\"}","VisibilityTimeout":"1"}'
    awslocal sqs create-queue --endpoint-url http://localhost:4566 --queue-name lgpd-protocolo-delecao-req.fifo --attributes '{"FifoQueue":"true","RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:sqs-dlq.fifo\",\"maxReceiveCount\":\"3\"}","VisibilityTimeout":"1"}'

    awslocal sqs list-queues --endpoint-url http://localhost:4566

    awslocal ses verify-email-identity --email-address sac.fast.n.foodious@gmail.com --endpoint-url=http://localhost:4566