namespace: default

application:
  name: fast-n-foodious-ms-pedido
  image: ottero/fast-n-foodious-ms-pedido:latest
  resources:
    limits:
      memory: "768Mi"
      cpu: "500m"

service:
  loadbalancer:
    port: 3001

mysql:
  name: mysql-pedido
  image: mysql:8.0
  mountPath: /var/lib/mysql-pedido
  resources:
    limits:
      memory: "768Mi"
      cpu: "500m"

configMap:
  data:
    NODE_ENV: prod
    MYSQL_HOST: mysql-pedido
    MYSQL_USER: fnf_user

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 70

pv:
  name: fast-n-foodious-ms-pedido-pv
  storage: 500Mi
  hostPath: /Users/renatorodrigues/mysql

pvc:
  name: fast-n-foodious-ms-pedido-pvc
  requests:
      storage: 500Mi

storageClassName: fast-n-foodious-ms-pedido-storage

secret:
  data:
    MYSQL_PASSWORD: Zm5mX3Bhc3M=
    MYSQL_ROOT_PASSWORD: Zm5mX3Bhc3M=